// Contas padrão para demo
export const DEMO_ACCOUNTS = {
  encarregado: {
    id: "ENC001",
    email: "maria.silva@email.ao",
    password: "enc123",
    nome: "Maria da Silva",
    alunoId: "ALU001",
    alunoNome: "João Manuel da Silva",
    alunoNumero: "2024001234",
    parentesco: "Mãe",
    telefone: "+244 912 345 678",
    foto: "/placeholder-user.jpg",
  },
  aluno: {
    id: "ALU001",
    numeroAluno: "2024001234",
    password: "aluno123",
    nome: "João Manuel da Silva",
    email: "joao.silva@aluno.ipmayombe.ao",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    turma: "IG-3A",
    turmaId: "TUR001",
    ano: 3,
    dataNascimento: "2003-05-15",
    genero: "Masculino",
    telefone: "+244 923 456 789",
    endereco: "Bairro Maianga, Luanda",
    encarregado: {
      nome: "Maria da Silva",
      telefone: "+244 912 345 678",
      email: "maria.silva@email.ao",
      parentesco: "Mãe",
    },
    foto: "/african-student.jpg",
    dataMatricula: "2022-02-15",
    estado: "Activo",
  },
  professor: {
    id: "PROF001",
    email: "maria.santos@ipmayombe.ao",
    password: "prof123",
    nome: "Profª. Maria dos Santos",
    departamento: "Ciências e Tecnologia",
    departamentoId: "DEP001",
    disciplinas: [
      { id: "DIS001", nome: "Programação Web", turmas: ["IG-3A", "IG-3B"] },
      { id: "DIS002", nome: "Base de Dados", turmas: ["IG-2A", "IG-2B"] },
      { id: "DIS003", nome: "Sistemas Operativos", turmas: ["IG-3A"] },
    ],
    telefone: "+244 934 567 890",
    formacao: "Mestrado em Engenharia Informática",
    dataContratacao: "2018-09-01",
    estado: "Activo",
    foto: "/african-professor.jpg",
  },
  admin: {
    id: "ADM001",
    email: "admin@ipmayombe.ao",
    password: "admin123",
    nome: "António Ferreira",
    cargo: "Administrador do Sistema",
    telefone: "+244 945 678 901",
    foto: "/african-administrator.jpg",
    permissoes: ["all"],
  },
}

// Anos Lectivos
export const ANOS_LECTIVOS = [
  { id: "AL001", nome: "2024/2025", inicio: "2024-09-01", fim: "2025-07-31", estado: "Activo" },
  { id: "AL002", nome: "2023/2024", inicio: "2023-09-01", fim: "2024-07-31", estado: "Encerrado" },
  { id: "AL003", nome: "2022/2023", inicio: "2022-09-01", fim: "2023-07-31", estado: "Encerrado" },
]

// Trimestres/Períodos
export const TRIMESTRES = [
  {
    id: "TRI001",
    nome: "1º Trimestre",
    anoLectivoId: "AL001",
    inicio: "2024-09-01",
    fim: "2024-12-15",
    estado: "Encerrado",
  },
  {
    id: "TRI002",
    nome: "2º Trimestre",
    anoLectivoId: "AL001",
    inicio: "2025-01-06",
    fim: "2025-04-05",
    estado: "Activo",
  },
  {
    id: "TRI003",
    nome: "3º Trimestre",
    anoLectivoId: "AL001",
    inicio: "2025-04-21",
    fim: "2025-07-15",
    estado: "Pendente",
  },
]

// Departamentos
export const DEPARTAMENTOS = [
  { id: "DEP001", nome: "Ciências e Tecnologia", coordenador: "Prof. Manuel Gomes", totalProfessores: 18 },
  { id: "DEP002", nome: "Ciências Exactas", coordenador: "Profª. Ana Costa", totalProfessores: 12 },
  { id: "DEP003", nome: "Ciências Sociais e Humanas", coordenador: "Prof. David Sousa", totalProfessores: 15 },
  { id: "DEP004", nome: "Saúde", coordenador: "Profª. Teresa Almeida", totalProfessores: 10 },
  { id: "DEP005", nome: "Artes e Ofícios", coordenador: "Prof. Carlos Mendes", totalProfessores: 13 },
]

// Cursos completos
export const CURSOS = [
  {
    id: "CUR001",
    nome: "Contabilidade",
    sigla: "CONT",
    descricao: "Curso de Contabilidade Financeira e Gestão",
    anos: 3,
    duracao: 3,
    estado: "Activo",
    coordenador: "Prof. Adilson Queta",
    totalAlunos: 145,
    totalTurmas: 4,
  },
  {
    id: "CUR002",
    nome: "Informática de Gestão",
    sigla: "IG",
    descricao: "Curso de Tecnologia da Informação com foco em Gestão",
    anos: 3,
    duracao: 3,
    estado: "Activo",
    coordenador: "Prof. Julio Nkosi",
    totalAlunos: 158,
    totalTurmas: 4,
  },
]

// Disciplinas completas
export const DISCIPLINAS_CONTABILIDADE = {
  "10": [
    { id: 1, nome: "Matemática", sigla: "MAT" },
    { id: 2, nome: "Língua Portuguesa", sigla: "LP" },
    { id: 4, nome: "Contabilidade Financeira", sigla: "CF" },
    { id: 8, nome: "Economia", sigla: "ECON" },
    { id: 6, nome: "Informática", sigla: "INFO" },
    { id: 7, nome: "Educação Física", sigla: "EF" },
    { id: 9, nome: "Língua Inglesa", sigla: "ING" },
    { id: 3, nome: "Direito Laboral Comercial", sigla: "DLC" },
    { id: 5, nome: "Organização e Gestão de Empresas", sigla: "OGE" },
    { id: 10, nome: "Física Aplicada à Indústria", sigla: "FAI" },
  ],
  "11": [
    { id: 11, nome: "Matemática", sigla: "MAT" },
    { id: 12, nome: "Língua Portuguesa", sigla: "LP" },
    { id: 13, nome: "Contabilidade Financeira", sigla: "CF" },
    { id: 14, nome: "Informática", sigla: "INFO" },
    { id: 15, nome: "Educação Física", sigla: "EF" },
    { id: 16, nome: "Organização e Gestão de Empresas", sigla: "OGE" },
    { id: 17, nome: "Noções de Direito", sigla: "ND" },
    { id: 18, nome: "Língua Inglesa", sigla: "ING" },
    { id: 19, nome: "Física Aplicada à Indústria", sigla: "FAI" },
  ],
  "12": [
    { id: 20, nome: "Matemática", sigla: "MAT" },
    { id: 21, nome: "Técnicas Contabilísticas Específicas", sigla: "TCE" },
    { id: 22, nome: "Contabilidade Analítica", sigla: "CA" },
    { id: 23, nome: "Direito Laboral Fiscal", sigla: "DLF" },
    { id: 24, nome: "Gestão Orçamental", sigla: "GO" },
    { id: 25, nome: "Organização e Gestão de Empresas", sigla: "OGE" },
    { id: 26, nome: "Projeto Tecnológico", sigla: "PT" },
    { id: 27, nome: "Auditoria, Estatística e Fiscalização", sigla: "AEF" },
  ],
}

export const DISCIPLINAS_INFORMATICA = {
  "10": [
    { id: 28, nome: "Técnicas de Linguagem de Programação", sigla: "TLP" },
    { id: 29, nome: "Tecnologias da Informação e Comunicação", sigla: "TIC" },
    { id: 30, nome: "Sistemas, Estruturas e Análise de Computadores", sigla: "SEAC" },
    { id: 31, nome: "Matemática", sigla: "MAT" },
    { id: 32, nome: "Língua Portuguesa", sigla: "LP" },
    { id: 33, nome: "Língua Inglesa", sigla: "ING" },
    { id: 34, nome: "Física", sigla: "FIS" },
    { id: 35, nome: "Desenho Técnico", sigla: "DT" },
    { id: 36, nome: "Eletrotecnia", sigla: "ELET" },
    { id: 37, nome: "Educação Física", sigla: "EF" },
  ],
  "11": [
    { id: 38, nome: "Língua Portuguesa", sigla: "LP" },
    { id: 39, nome: "Física", sigla: "FIS" },
    { id: 40, nome: "Matemática", sigla: "MAT" },
    { id: 41, nome: "Sistemas, Estruturas e Análise de Computadores", sigla: "SEAC" },
    { id: 42, nome: "Física Aplicada à Indústria", sigla: "FAI" },
    { id: 43, nome: "Técnicas de Linguagem de Programação", sigla: "TLP" },
    { id: 44, nome: "Língua Inglesa", sigla: "ING" },
    { id: 45, nome: "Química", sigla: "QUIM" },
    { id: 46, nome: "Eletrotecnia", sigla: "ELET" },
    { id: 47, nome: "Educação Física", sigla: "EF" },
  ],
  "12": [
    { id: 48, nome: "Português", sigla: "PT" },
    { id: 49, nome: "Técnicas de Linguagem de Programação", sigla: "TLP" },
    { id: 50, nome: "Redes, Telecomunicações e Eletrónica Industrial", sigla: "TREI" },
    { id: 51, nome: "Física Aplicada à Indústria", sigla: "FAI" },
    { id: 52, nome: "Sistemas, Estruturas e Análise de Computadores", sigla: "SEAC" },
    { id: 53, nome: "Matemática", sigla: "MAT" },
    { id: 54, nome: "Química Orgânica", sigla: "QO" },
    { id: 55, nome: "Empreendedorismo", sigla: "EMP" },
    { id: 56, nome: "Organização e Gestão da Informática", sigla: "OGI" },
  ],
}

export const DISCIPLINAS = [
  // Contabilidade - 10°
  {
    id: 1,
    nome: "Matemática",
    sigla: "MAT",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 10,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 2,
    nome: "Língua Portuguesa",
    sigla: "LP",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 10,
    cargaHoraria: 3,
    creditos: 3,
    tipo: "Nuclear",
  },
  {
    id: 3,
    nome: "Direito Laboral Comercial",
    sigla: "DLC",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 10,
    cargaHoraria: 2,
    creditos: 3,
    tipo: "Nuclear",
  },
  {
    id: 4,
    nome: "Contabilidade Financeira",
    sigla: "CF",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 10,
    cargaHoraria: 4,
    creditos: 5,
    tipo: "Nuclear",
  },
  {
    id: 5,
    nome: "Organização e Gestão de Empresas",
    sigla: "OGE",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 10,
    cargaHoraria: 2,
    creditos: 3,
    tipo: "Nuclear",
  },
  {
    id: 6,
    nome: "Informática",
    sigla: "INFO",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 10,
    cargaHoraria: 3,
    creditos: 3,
    tipo: "Complementar",
  },
  {
    id: 7,
    nome: "Educação Física",
    sigla: "EF",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 10,
    cargaHoraria: 2,
    creditos: 2,
    tipo: "Complementar",
  },
  {
    id: 8,
    nome: "Economia",
    sigla: "ECON",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 10,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 9,
    nome: "Língua Inglesa",
    sigla: "ING",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 10,
    cargaHoraria: 3,
    creditos: 3,
    tipo: "Complementar",
  },
  {
    id: 10,
    nome: "Física Aplicada à Indústria",
    sigla: "FAI",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 10,
    cargaHoraria: 2,
    creditos: 2,
    tipo: "Complementar",
  },

  // Contabilidade - 11°
  {
    id: 11,
    nome: "Matemática",
    sigla: "MAT",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 11,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 12,
    nome: "Língua Portuguesa",
    sigla: "LP",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 11,
    cargaHoraria: 3,
    creditos: 3,
    tipo: "Nuclear",
  },
  {
    id: 13,
    nome: "Contabilidade Financeira",
    sigla: "CF",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 11,
    cargaHoraria: 4,
    creditos: 5,
    tipo: "Nuclear",
  },
  {
    id: 14,
    nome: "Informática",
    sigla: "INFO",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 11,
    cargaHoraria: 3,
    creditos: 3,
    tipo: "Complementar",
  },
  {
    id: 15,
    nome: "Educação Física",
    sigla: "EF",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 11,
    cargaHoraria: 2,
    creditos: 2,
    tipo: "Complementar",
  },
  {
    id: 16,
    nome: "Organização e Gestão de Empresas",
    sigla: "OGE",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 11,
    cargaHoraria: 2,
    creditos: 3,
    tipo: "Nuclear",
  },
  {
    id: 17,
    nome: "Noções de Direito",
    sigla: "ND",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 11,
    cargaHoraria: 2,
    creditos: 2,
    tipo: "Complementar",
  },
  {
    id: 18,
    nome: "Língua Inglesa",
    sigla: "ING",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 11,
    cargaHoraria: 3,
    creditos: 3,
    tipo: "Complementar",
  },
  {
    id: 19,
    nome: "Física Aplicada à Indústria",
    sigla: "FAI",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 11,
    cargaHoraria: 2,
    creditos: 2,
    tipo: "Complementar",
  },

  // Contabilidade - 12°
  {
    id: 20,
    nome: "Matemática",
    sigla: "MAT",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 12,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 21,
    nome: "Técnicas Contabilísticas Específicas",
    sigla: "TCE",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 12,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 22,
    nome: "Contabilidade Analítica",
    sigla: "CA",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 12,
    cargaHoraria: 4,
    creditos: 5,
    tipo: "Nuclear",
  },
  {
    id: 23,
    nome: "Direito Laboral Fiscal",
    sigla: "DLF",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 12,
    cargaHoraria: 2,
    creditos: 3,
    tipo: "Nuclear",
  },
  {
    id: 24,
    nome: "Gestão Orçamental",
    sigla: "GO",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 12,
    cargaHoraria: 2,
    creditos: 3,
    tipo: "Nuclear",
  },
  {
    id: 25,
    nome: "Organização e Gestão de Empresas",
    sigla: "OGE",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 12,
    cargaHoraria: 2,
    creditos: 3,
    tipo: "Nuclear",
  },
  {
    id: 26,
    nome: "Projeto Tecnológico",
    sigla: "PT",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 12,
    cargaHoraria: 2,
    creditos: 3,
    tipo: "Complementar",
  },
  {
    id: 27,
    nome: "Auditoria, Estatística e Fiscalização",
    sigla: "AEFE",
    curso: "Contabilidade",
    cursoId: "CUR001",
    ano: 12,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },

  // Informática de Gestão - 10°
  {
    id: 28,
    nome: "Técnicas de Linguagem de Programação",
    sigla: "TLP",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 10,
    cargaHoraria: 4,
    creditos: 5,
    tipo: "Nuclear",
  },
  {
    id: 29,
    nome: "Tecnologias da Informação e Comunicação",
    sigla: "TIC",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 10,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 30,
    nome: "Sistemas, Estruturas e Análise de Computadores",
    sigla: "SEAC",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 10,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 31,
    nome: "Matemática",
    sigla: "MAT",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 10,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 32,
    nome: "Língua Portuguesa",
    sigla: "LP",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 10,
    cargaHoraria: 3,
    creditos: 3,
    tipo: "Nuclear",
  },
  {
    id: 33,
    nome: "Língua Inglesa",
    sigla: "ING",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 10,
    cargaHoraria: 3,
    creditos: 3,
    tipo: "Complementar",
  },
  {
    id: 34,
    nome: "Física",
    sigla: "FIS",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 10,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 35,
    nome: "Desenho Técnico",
    sigla: "DT",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 10,
    cargaHoraria: 2,
    creditos: 2,
    tipo: "Complementar",
  },
  {
    id: 36,
    nome: "Eletrotecnia",
    sigla: "ELET",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 10,
    cargaHoraria: 2,
    creditos: 3,
    tipo: "Nuclear",
  },
  {
    id: 37,
    nome: "Educação Física",
    sigla: "EF",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 10,
    cargaHoraria: 2,
    creditos: 2,
    tipo: "Complementar",
  },

  // Informática de Gestão - 11°
  {
    id: 38,
    nome: "Língua Portuguesa",
    sigla: "LP",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 11,
    cargaHoraria: 3,
    creditos: 3,
    tipo: "Nuclear",
  },
  {
    id: 39,
    nome: "Física",
    sigla: "FIS",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 11,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 40,
    nome: "Matemática",
    sigla: "MAT",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 11,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 41,
    nome: "Sistemas, Estruturas e Análise de Computadores",
    sigla: "SEAC",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 11,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 42,
    nome: "Física Aplicada à Indústria",
    sigla: "FAI",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 11,
    cargaHoraria: 2,
    creditos: 3,
    tipo: "Complementar",
  },
  {
    id: 43,
    nome: "Técnicas de Linguagem de Programação",
    sigla: "TLP",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 11,
    cargaHoraria: 4,
    creditos: 5,
    tipo: "Nuclear",
  },
  {
    id: 44,
    nome: "Língua Inglesa",
    sigla: "ING",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 11,
    cargaHoraria: 3,
    creditos: 3,
    tipo: "Complementar",
  },
  {
    id: 45,
    nome: "Química",
    sigla: "QUIM",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 11,
    cargaHoraria: 2,
    creditos: 3,
    tipo: "Complementar",
  },
  {
    id: 46,
    nome: "Eletrotecnia",
    sigla: "ELET",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 11,
    cargaHoraria: 2,
    creditos: 3,
    tipo: "Nuclear",
  },
  {
    id: 47,
    nome: "Educação Física",
    sigla: "EF",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 11,
    cargaHoraria: 2,
    creditos: 2,
    tipo: "Complementar",
  },

  // Informática de Gestão - 12°
  {
    id: 48,
    nome: "Português",
    sigla: "PT",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 12,
    cargaHoraria: 3,
    creditos: 3,
    tipo: "Nuclear",
  },
  {
    id: 49,
    nome: "Técnicas de Linguagem de Programação",
    sigla: "TLP",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 12,
    cargaHoraria: 4,
    creditos: 5,
    tipo: "Nuclear",
  },
  {
    id: 50,
    nome: "Redes, Telecomunicações e Eletrónica Industrial",
    sigla: "TREI",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 12,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 51,
    nome: "Física Aplicada à Indústria",
    sigla: "FAI",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 12,
    cargaHoraria: 2,
    creditos: 3,
    tipo: "Complementar",
  },
  {
    id: 52,
    nome: "Sistemas, Estruturas e Análise de Computadores",
    sigla: "SEAC",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 12,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 53,
    nome: "Matemática",
    sigla: "MAT",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 12,
    cargaHoraria: 3,
    creditos: 4,
    tipo: "Nuclear",
  },
  {
    id: 54,
    nome: "Química Orgânica",
    sigla: "QO",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 12,
    cargaHoraria: 2,
    creditos: 3,
    tipo: "Complementar",
  },
  {
    id: 55,
    nome: "Empreendedorismo",
    sigla: "EMP",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 12,
    cargaHoraria: 2,
    creditos: 2,
    tipo: "Complementar",
  },
  {
    id: 56,
    nome: "Organização e Gestão da Informática",
    sigla: "OGI",
    curso: "Informática de Gestão",
    cursoId: "CUR002",
    ano: 12,
    cargaHoraria: 2,
    creditos: 3,
    tipo: "Nuclear",
  },
]

// Turmas completas
export const TURMAS = [
  {
    id: "TUR001",
    nome: "IG-3A",
    cursoId: "CUR002",
    ano: 3,
    turno: "Manhã",
    sala: "Sala 301",
    totalAlunos: 28,
    directordeTurma: "Profª. Maria Santos",
  },
  {
    id: "TUR002",
    nome: "IG-3B",
    cursoId: "CUR002",
    ano: 3,
    turno: "Tarde",
    sala: "Sala 302",
    totalAlunos: 26,
    directordeTurma: "Prof. Carlos Mendes",
  },
  {
    id: "TUR003",
    nome: "IG-2A",
    cursoId: "CUR002",
    ano: 2,
    turno: "Manhã",
    sala: "Sala 201",
    totalAlunos: 32,
    directordeTurma: "Prof. Manuel Gomes",
  },
  {
    id: "TUR004",
    nome: "IG-2B",
    cursoId: "CUR002",
    ano: 2,
    turno: "Tarde",
    sala: "Sala 202",
    totalAlunos: 30,
    directordeTurma: "Profª. Ana Costa",
  },
  {
    id: "TUR005",
    nome: "CONT-3A",
    cursoId: "CUR001",
    ano: 3,
    turno: "Manhã",
    sala: "Sala 101",
    totalAlunos: 24,
    directordeTurma: "Prof. António Silva",
  },
]

// Professores completos
export const PROFESSORES = [
  {
    id: "PROF001",
    nome: "Maria dos Santos",
    email: "maria.santos@ipmayombe.ao",
    departamento: "Ciências e Tecnologia",
    disciplinas: ["Programação Web", "Base de Dados", "Sistemas Operativos"],
    turmas: ["IG-3A", "IG-2B", "CONT-3A"],
    telefone: "+244 934 567 890",
    estado: "Activo",
    foto: "/african-professor.jpg",
  },
  {
    id: "PROF002",
    nome: "Carlos Mendes",
    email: "carlos.mendes@ipmayombe.ao",
    departamento: "Ciências e Tecnologia",
    disciplinas: ["Electricidade Básica", "Circuitos Eléctricos"],
    turmas: ["ELE-2A", "ELE-3A"],
    telefone: "+244 935 678 901",
    estado: "Activo",
    foto: "/african-male-professor.png",
  },
  {
    id: "PROF003",
    nome: "Manuel Gomes",
    email: "manuel.gomes@ipmayombe.ao",
    departamento: "Ciências e Tecnologia",
    disciplinas: ["Algoritmos", "Estruturas de Dados"],
    turmas: ["IG-1A", "IG-2A"],
    telefone: "+244 936 789 012",
    estado: "Activo",
    foto: "/african-male-professor-2.jpg",
  },
  {
    id: "PROF004",
    nome: "Ana Costa",
    email: "ana.costa@ipmayombe.ao",
    departamento: "Ciências Exactas",
    disciplinas: ["Matemática Aplicada", "Estatística"],
    turmas: ["IG-1A", "CONT-1A", "IG-1A"],
    telefone: "+244 937 890 123",
    estado: "Activo",
    foto: "/african-female-professor.jpg",
  },
  {
    id: "PROF005",
    nome: "Pedro Alves",
    email: "pedro.alves@ipmayombe.ao",
    departamento: "Ciências e Tecnologia",
    disciplinas: ["Redes de Computadores", "Segurança Informática"],
    turmas: ["IG-3A", "CONT-3A"],
    telefone: "+244 938 901 234",
    estado: "Licença",
    foto: "/african-male-professor-3.jpg",
  },
  {
    id: "PROF006",
    nome: "Teresa Almeida",
    email: "teresa.almeida@ipmayombe.ao",
    departamento: "Saúde",
    disciplinas: ["Anatomia", "Fisiologia"],
    turmas: ["ENF-1A", "ENF-2A"],
    telefone: "+244 939 012 345",
    estado: "Activo",
    foto: "/african-female-professor-2.jpg",
  },
  {
    id: "PROF007",
    nome: "David Sousa",
    email: "david.sousa@ipmayombe.ao",
    departamento: "Ciências Sociais e Humanas",
    disciplinas: ["Inglês Técnico", "Comunicação Empresarial"],
    turmas: ["IG-2A", "CONT-2A"],
    telefone: "+244 940 123 456",
    estado: "Activo",
    foto: "/african-male-professor-4.jpg",
  },
  {
    id: "PROF008",
    nome: "António Silva",
    email: "antonio.silva@ipmayombe.ao",
    departamento: "Ciências Sociais e Humanas",
    disciplinas: ["Contabilidade Geral", "Gestão Financeira"],
    turmas: ["CONT-1A", "CONT-2A", "CONT-3A"],
    telefone: "+244 941 234 567",
    estado: "Activo",
    foto: "/african-male-professor-5.jpg",
  },
]

// Alunos completos
export const ALUNOS = [
  {
    id: "ALU001",
    numero: "2024001234",
    nome: "João Manuel da Silva",
    email: "joao.silva@aluno.ipmayombe.ao",
    curso: "Informática de Gestão",
    turma: "IG-3A",
    ano: 3,
    estado: "Activo",
    media: 15.8,
    foto: "/african-student.jpg",
  },
  {
    id: "ALU002",
    numero: "2024001235",
    nome: "Ana Beatriz Ferreira",
    email: "ana.ferreira@aluno.ipmayombe.ao",
    curso: "Informática de Gestão",
    turma: "IG-3A",
    ano: 3,
    estado: "Activo",
    media: 14.2,
    foto: "/african-female-student.jpg",
  },
  {
    id: "ALU003",
    numero: "2024001236",
    nome: "Pedro Miguel Santos",
    email: "pedro.santos@aluno.ipmayombe.ao",
    curso: "Informática de Gestão",
    turma: "IG-3A",
    ano: 3,
    estado: "Activo",
    media: 12.5,
    foto: "/african-male-student-2.jpg",
  },
  {
    id: "ALU004",
    numero: "2024001237",
    nome: "Maria José Costa",
    email: "maria.costa@aluno.ipmayombe.ao",
    curso: "Informática de Gestão",
    turma: "IG-3A",
    ano: 3,
    estado: "Activo",
    media: 17.8,
    foto: "/african-female-student-2.jpg",
  },
  {
    id: "ALU005",
    numero: "2024001238",
    nome: "Carlos Eduardo Gomes",
    email: "carlos.gomes@aluno.ipmayombe.ao",
    curso: "Informática de Gestão",
    turma: "IG-3A",
    ano: 3,
    estado: "Activo",
    media: 9.2,
    foto: "/african-male-student-3.jpg",
  },
  {
    id: "ALU006",
    numero: "2024001239",
    nome: "Luísa Helena Martins",
    email: "luisa.martins@aluno.ipmayombe.ao",
    curso: "Contabilidade",
    turma: "CONT-3A",
    ano: 3,
    estado: "Activo",
    media: 16.3,
    foto: "/african-female-student-3.jpg",
  },
  {
    id: "ALU007",
    numero: "2024001240",
    nome: "Ricardo António Sousa",
    email: "ricardo.sousa@aluno.ipmayombe.ao",
    curso: "Contabilidade",
    turma: "CONT-1A",
    ano: 1,
    estado: "Activo",
    media: 13.9,
    foto: "/african-male-student-4.jpg",
  },
  {
    id: "ALU008",
    numero: "2024001241",
    nome: "Sofia Margarida Alves",
    email: "sofia.alves@aluno.ipmayombe.ao",
    curso: "Contabilidade",
    turma: "CONT-2A",
    ano: 2,
    estado: "Activo",
    media: 15.1,
    foto: "/african-female-student-4.jpg",
  },
  {
    id: "ALU009",
    numero: "2024001242",
    nome: "Fernando José Lima",
    email: "fernando.lima@aluno.ipmayombe.ao",
    curso: "Electricidade",
    turma: "ELE-2A",
    ano: 2,
    estado: "Inactivo",
    media: 11.4,
    foto: "/african-male-student-5.jpg",
  },
  {
    id: "ALU010",
    numero: "2024001243",
    nome: "Catarina Isabel Rocha",
    email: "catarina.rocha@aluno.ipmayombe.ao",
    curso: "Mecânica Auto",
    turma: "MA-1A",
    ano: 1,
    estado: "Activo",
    media: 14.7,
    foto: "/african-female-student-5.jpg",
  },
]

// Encarregados de Educação
export const ENCARREGADOS = [
  {
    id: "ENC001",
    nome: "Maria da Silva",
    email: "maria.silva@email.ao",
    telefone: "+244 912 345 678",
    alunoId: "ALU001",
    parentesco: "Mãe",
  },
  {
    id: "ENC002",
    nome: "José Ferreira",
    email: "jose.ferreira@email.ao",
    telefone: "+244 913 456 789",
    alunoId: "ALU002",
    parentesco: "Pai",
  },
  {
    id: "ENC003",
    nome: "Ana Santos",
    email: "ana.santos@email.ao",
    telefone: "+244 914 567 890",
    alunoId: "ALU003",
    parentesco: "Mãe",
  },
  {
    id: "ENC004",
    nome: "Manuel Costa",
    email: "manuel.costa@email.ao",
    telefone: "+244 915 678 901",
    alunoId: "ALU004",
    parentesco: "Pai",
  },
  {
    id: "ENC005",
    nome: "Teresa Gomes",
    email: "teresa.gomes@email.ao",
    telefone: "+244 916 789 012",
    alunoId: "ALU005",
    parentesco: "Mãe",
  },
]

// Notas com estado de validação
export const NOTAS_PENDENTES = [
  {
    id: "NOT001",
    alunoId: "ALU001",
    alunoNome: "João Manuel da Silva",
    disciplinaId: "DIS001",
    disciplinaNome: "Programação Web",
    turma: "IG-3A",
    trimestre: "2º Trimestre",
    p1: 16,
    p2: 18,
    trabalho: 17,
    exame: null,
    media: null,
    estado: "Pendente",
    professorId: "PROF001",
    professorNome: "Profª. Maria Santos",
    dataLancamento: "2025-02-10",
    observacoes: "",
  },
  {
    id: "NOT002",
    alunoId: "ALU002",
    alunoNome: "Ana Beatriz Ferreira",
    disciplinaId: "DIS001",
    disciplinaNome: "Programação Web",
    turma: "IG-3A",
    trimestre: "2º Trimestre",
    p1: 14,
    p2: 15,
    trabalho: 16,
    exame: null,
    media: null,
    estado: "Pendente",
    professorId: "PROF001",
    professorNome: "Profª. Maria Santos",
    dataLancamento: "2025-02-10",
    observacoes: "",
  },
  {
    id: "NOT003",
    alunoId: "ALU003",
    alunoNome: "Pedro Miguel Santos",
    disciplinaId: "DIS001",
    disciplinaNome: "Programação Web",
    turma: "IG-3A",
    trimestre: "2º Trimestre",
    p1: 12,
    p2: 10,
    trabalho: 13,
    exame: null,
    media: null,
    estado: "Pendente",
    professorId: "PROF001",
    professorNome: "Profª. Maria Santos",
    dataLancamento: "2025-02-10",
    observacoes: "",
  },
  {
    id: "NOT004",
    alunoId: "ALU004",
    alunoNome: "Maria José Costa",
    disciplinaId: "DIS002",
    disciplinaNome: "Base de Dados",
    turma: "IG-2B",
    trimestre: "2º Trimestre",
    p1: 18,
    p2: 19,
    trabalho: 18,
    exame: 17,
    media: 18.0,
    estado: "Aprovado",
    professorId: "PROF001",
    professorNome: "Profª. Maria Santos",
    dataLancamento: "2025-02-08",
    observacoes: "Excelente desempenho",
  },
  {
    id: "NOT005",
    alunoId: "ALU005",
    alunoNome: "Carlos Eduardo Gomes",
    disciplinaId: "DIS002",
    disciplinaNome: "Base de Dados",
    turma: "IG-2B",
    trimestre: "2º Trimestre",
    p1: 8,
    p2: 7,
    trabalho: 10,
    exame: null,
    media: null,
    estado: "Rejeitado",
    professorId: "PROF001",
    professorNome: "Profª. Maria Santos",
    dataLancamento: "2025-02-08",
    observacoes: "Verificar nota da P2 - possível erro",
  },
]

// Notas completas dos alunos
export const ALUNO_DISCIPLINAS = [
  {
    id: 1,
    nome: "Programação Web",
    professor: "Profª. Maria dos Santos",
    notas: { p1: 16, p2: 18, trabalho: 17, exame: 15 },
    media: 16.5,
    estado: "Aprovado",
    trimestre: "1º Trimestre",
  },
  {
    id: 2,
    nome: "Base de Dados",
    professor: "Prof. Carlos Mendes",
    notas: { p1: 14, p2: 15, trabalho: 16, exame: 14 },
    media: 14.75,
    estado: "Aprovado",
    trimestre: "1º Trimestre",
  },
  {
    id: 3,
    nome: "Sistemas Operativos",
    professor: "Prof. Manuel Gomes",
    notas: { p1: 12, p2: 13, trabalho: 14, exame: null },
    media: null,
    estado: "Em curso",
    trimestre: "2º Trimestre",
  },
  {
    id: 4,
    nome: "Redes de Computadores",
    professor: "Prof. Pedro Alves",
    notas: { p1: 17, p2: 16, trabalho: 18, exame: 16 },
    media: 16.75,
    estado: "Aprovado",
    trimestre: "1º Trimestre",
  },
  {
    id: 5,
    nome: "Matemática Aplicada",
    professor: "Profª. Ana Costa",
    notas: { p1: 10, p2: 11, trabalho: 12, exame: null },
    media: null,
    estado: "Em curso",
    trimestre: "2º Trimestre",
  },
  {
    id: 6,
    nome: "Inglês Técnico",
    professor: "Prof. David Sousa",
    notas: { p1: 15, p2: 16, trabalho: 17, exame: 15 },
    media: 15.75,
    estado: "Aprovado",
    trimestre: "1º Trimestre",
  },
]

// Histórico de notas anuais
export const HISTORICO_NOTAS = [
  { anoLectivo: "2022/2023", ano: 1, mediaAnual: 14.2, estado: "Aprovado", disciplinas: 8, aprovadas: 8 },
  { anoLectivo: "2023/2024", ano: 2, mediaAnual: 15.1, estado: "Aprovado", disciplinas: 8, aprovadas: 8 },
  { anoLectivo: "2024/2025", ano: 3, mediaAnual: null, estado: "Em curso", disciplinas: 6, aprovadas: 4 },
]

// Horário semanal do aluno
export const ALUNO_HORARIO = [
  {
    dia: "Segunda",
    horarios: [
      { hora: "08:00 - 10:00", disciplina: "Programação Web", sala: "Lab 1", professor: "Profª. Maria Santos" },
      { hora: "10:30 - 12:30", disciplina: "Base de Dados", sala: "Sala 205", professor: "Profª. Maria Santos" },
    ],
  },
  {
    dia: "Terça",
    horarios: [
      { hora: "08:00 - 10:00", disciplina: "Sistemas Operativos", sala: "Lab 2", professor: "Prof. Manuel Gomes" },
      { hora: "14:00 - 16:00", disciplina: "Redes de Computadores", sala: "Lab 3", professor: "Prof. Pedro Alves" },
    ],
  },
  {
    dia: "Quarta",
    horarios: [
      { hora: "08:00 - 10:00", disciplina: "Matemática Aplicada", sala: "Sala 101", professor: "Profª. Ana Costa" },
      { hora: "10:30 - 12:30", disciplina: "Inglês Técnico", sala: "Sala 102", professor: "Prof. David Sousa" },
    ],
  },
  {
    dia: "Quinta",
    horarios: [
      { hora: "08:00 - 10:00", disciplina: "Programação Web", sala: "Lab 1", professor: "Profª. Maria Santos" },
      { hora: "14:00 - 16:00", disciplina: "Base de Dados", sala: "Lab 2", professor: "Profª. Maria Santos" },
    ],
  },
  {
    dia: "Sexta",
    horarios: [
      { hora: "08:00 - 10:00", disciplina: "Sistemas Operativos", sala: "Lab 2", professor: "Prof. Manuel Gomes" },
      { hora: "10:30 - 12:30", disciplina: "Redes de Computadores", sala: "Lab 3", professor: "Prof. Pedro Alves" },
    ],
  },
]

// Avisos e comunicados
export const AVISOS = [
  {
    id: 1,
    titulo: "Exames do 2º Trimestre",
    descricao:
      "Os exames do 2º trimestre iniciam no dia 25 de Março. Consultem o calendário completo no portal académico.",
    data: "2025-03-01",
    tipo: "importante",
    destinatarios: "todos",
    autor: "Direcção Académica",
  },
  {
    id: 2,
    titulo: "Inscrição em Disciplinas",
    descricao: "O período de inscrição em disciplinas optativas para o 3º trimestre está aberto até 15 de Março.",
    data: "2025-02-28",
    tipo: "info",
    destinatarios: "alunos",
    autor: "Secretaria",
  },
  {
    id: 3,
    titulo: "Palestra de Empregabilidade",
    descricao: "Palestra sobre oportunidades de emprego no sector tecnológico angolano. Auditório Principal, 18h.",
    data: "2025-03-05",
    tipo: "evento",
    destinatarios: "alunos",
    autor: "Gabinete de Estágios",
  },
  {
    id: 4,
    titulo: "Reunião de Professores",
    descricao: "Reunião geral de professores no dia 10 de Março às 14h na Sala de Conferências.",
    data: "2025-03-02",
    tipo: "importante",
    destinatarios: "professores",
    autor: "Direcção",
  },
  {
    id: 5,
    titulo: "Manutenção do Sistema",
    descricao: "O sistema estará indisponível no domingo das 02h às 06h para manutenção programada.",
    data: "2025-03-01",
    tipo: "info",
    destinatarios: "todos",
    autor: "TI",
  },
]

// Mensagens internas
export const MENSAGENS = [
  {
    id: "MSG001",
    de: "Secretaria",
    deId: "SEC001",
    para: "Profª. Maria Santos",
    paraId: "PROF001",
    assunto: "Confirmação de Horário",
    mensagem: "Por favor confirme a disponibilidade para as aulas de reposição.",
    data: "2025-03-01",
    lida: false,
    tipo: "recebida",
  },
  {
    id: "MSG002",
    de: "Profª. Maria Santos",
    deId: "PROF001",
    para: "Admin",
    paraId: "ADM001",
    assunto: "Solicitação de Recursos",
    mensagem: "Solicito a instalação de software adicional no Lab 1.",
    data: "2025-02-28",
    lida: true,
    tipo: "enviada",
  },
  {
    id: "MSG003",
    de: "Admin",
    deId: "ADM001",
    para: "Profª. Maria Santos",
    paraId: "PROF001",
    assunto: "RE: Solicitação de Recursos",
    mensagem: "Pedido aprovado. A instalação será feita esta semana.",
    data: "2025-02-28",
    lida: true,
    tipo: "recebida",
  },
]

// Turmas do professor
export const PROFESSOR_TURMAS = [
  {
    id: "TUR001",
    nome: "IG-3A",
    curso: "Informática de Gestão",
    ano: 3,
    disciplina: "Programação Web",
    totalAlunos: 28,
    mediaGeral: 14.5,
    notasPendentes: 5,
  },
  {
    id: "TUR002",
    nome: "IG-2A",
    curso: "Informática de Gestão",
    ano: 2,
    disciplina: "Base de Dados",
    totalAlunos: 26,
    mediaGeral: 13.8,
    notasPendentes: 8,
  },
  {
    id: "TUR003",
    nome: "CONT-3A",
    curso: "Contabilidade",
    ano: 3,
    disciplina: "Contabilidade Analítica",
    totalAlunos: 24,
    mediaGeral: 14.2,
    notasPendentes: 3,
  },
]

// Alunos de uma turma para lançamento de notas
export const TURMA_ALUNOS = [
  {
    id: 1,
    numero: "2024001234",
    nome: "João Manuel da Silva",
    p1: 16,
    p2: 18,
    trabalho: 17,
    exame: null,
    media: null,
    estado: "Pendente",
    foto: "/african-student.jpg",
  },
  {
    id: 2,
    numero: "2024001235",
    nome: "Ana Beatriz Ferreira",
    p1: 14,
    p2: 15,
    trabalho: 16,
    exame: null,
    media: null,
    estado: "Pendente",
    foto: "/african-female-student.jpg",
  },
  {
    id: 3,
    numero: "2024001236",
    nome: "Pedro Miguel Santos",
    p1: 12,
    p2: 10,
    trabalho: 13,
    exame: null,
    media: null,
    estado: "Pendente",
    foto: "/placeholder.svg?height=40&width=40",
  },
  {
    id: 4,
    numero: "2024001237",
    nome: "Maria José Costa",
    p1: 18,
    p2: 19,
    trabalho: 18,
    exame: 17,
    media: 18.0,
    estado: "Aprovado",
    foto: "/african-female-student-2.jpg",
  },
  {
    id: 5,
    numero: "2024001238",
    nome: "Carlos Eduardo Gomes",
    p1: 8,
    p2: 7,
    trabalho: 10,
    exame: null,
    media: null,
    estado: "Rascunho",
    foto: "/african-male-student-2.jpg",
  },
  {
    id: 6,
    numero: "2024001239",
    nome: "Luísa Helena Martins",
    p1: 15,
    p2: 16,
    trabalho: 14,
    exame: 15,
    media: 15.0,
    estado: "Aprovado",
    foto: "/african-female-student-3.jpg",
  },
  {
    id: 7,
    numero: "2024001240",
    nome: "Ricardo António Sousa",
    p1: 13,
    p2: 14,
    trabalho: 15,
    exame: 13,
    media: 13.75,
    estado: "Aprovado",
    foto: "/african-male-student-3.jpg",
  },
  {
    id: 8,
    numero: "2024001241",
    nome: "Sofia Margarida Alves",
    p1: 17,
    p2: 16,
    trabalho: 18,
    exame: 16,
    media: 16.75,
    estado: "Aprovado",
    foto: "/african-female-student-4.jpg",
  },
]

// Estatísticas gerais do admin
export const ADMIN_STATS = {
  totalAlunos: 1247,
  alunosActivos: 1189,
  alunosInactivos: 58,
  totalProfessores: 68,
  professorActivos: 65,
  totalCursos: 12,
  totalTurmas: 45,
  totalDisciplinas: 87,
  taxaAprovacao: 87.3,
  mediaGeral: 14.2,
  notasLancadas: 4523,
  notasPendentes: 156,
  boletinsGerados: 1089,
}

// Configurações do sistema
export const CONFIGURACOES = {
  escola: {
    nome: "Instituto Politécnico do Mayombe",
    sigla: "IPM",
    endereco: "Buco Zau, Cabinda, Angola",
    telefone: "+244 222 123 456",
    email: "geral@ipmayombe.ao",
    website: "www.ipmayombe.ao",
    logo: "/placeholder.svg?height=100&width=100",
  },
  academico: {
    mediaMinima: 10,
    pesoP1: 20,
    pesoP2: 20,
    pesoTrabalho: 20,
    pesoExame: 40,
    notaMaxima: 20,
    notaMinima: 0,
    decimais: 2,
  },
  sistema: {
    tema: "claro",
    idioma: "pt-AO",
    formatoData: "dd/MM/yyyy",
    moeda: "AOA",
  },
}

// Evolução de dados para gráficos
export const EVOLUCAO_NOTAS = [
  { mes: "Set", media: 12.5, aprovados: 78, reprovados: 22 },
  { mes: "Out", media: 13.2, aprovados: 82, reprovados: 18 },
  { mes: "Nov", media: 14.1, aprovados: 85, reprovados: 15 },
  { mes: "Dez", media: 14.8, aprovados: 87, reprovados: 13 },
  { mes: "Jan", media: 15.5, aprovados: 89, reprovados: 11 },
  { mes: "Fev", media: 15.2, aprovados: 88, reprovados: 12 },
]

export const EVOLUCAO_MATRICULAS = [
  { ano: "2020", alunos: 890, professores: 52 },
  { ano: "2021", alunos: 1023, professores: 58 },
  { ano: "2022", alunos: 1156, professores: 62 },
  { ano: "2023", alunos: 1189, professores: 65 },
  { ano: "2024", alunos: 1247, professores: 68 },
]

export const DISTRIBUICAO_CURSOS = [
  { nome: "Contabilidade", sigla: "CONT", value: 125 },
  { nome: "Informática de Gestão", sigla: "IG", value: 138 },
]

export const DESEMPENHO_DISCIPLINAS = [
  { disciplina: "Prog. Web", media: 15.2, aprovados: 92 },
  { disciplina: "Base Dados", media: 14.1, aprovados: 88 },
  { disciplina: "Sist. Op.", media: 13.8, aprovados: 85 },
  { disciplina: "Redes", media: 14.5, aprovados: 87 },
  { disciplina: "Matemática", media: 12.3, aprovados: 76 },
  { disciplina: "Inglês", media: 15.8, aprovados: 94 },
]

export const COMPARATIVO_TRIMESTRES = [
  { turma: "IG-3A", t1: 14.2, t2: 15.1, t3: null },
  { turma: "IG-3B", t1: 13.8, t2: 14.5, t3: null },
  { turma: "IG-2A", t1: 14.5, t2: 14.8, t3: null },
  { turma: "EI-3A", t1: 15.2, t2: 15.6, t3: null },
  { turma: "CG-1A", t1: 13.1, t2: 13.9, t3: null },
]

// ─── Módulo 3: Exames e Provas ────────────────────────────────────────────────

export const EXAMES = [
  {
    id: "EXM001",
    tipo: "Exame",
    disciplinaId: "DIS001",
    disciplinaNome: "Programação Web",
    turmaId: "TUR001",
    turmaNome: "IG-3A",
    trimestre: "2º Trimestre",
    data: "2025-03-25",
    hora: "08:00",
    duracao: 120,
    sala: "Lab 1",
    professorId: "PROF001",
    professorNome: "Profª. Maria Santos",
    estado: "Programado",
    totalAlunos: 28,
    mediaResultado: null,
  },
  {
    id: "EXM002",
    tipo: "Teste",
    disciplinaId: "DIS002",
    disciplinaNome: "Base de Dados",
    turmaId: "TUR002",
    turmaNome: "IG-2A",
    trimestre: "2º Trimestre",
    data: "2025-03-20",
    hora: "10:30",
    duracao: 90,
    sala: "Sala 205",
    professorId: "PROF001",
    professorNome: "Profª. Maria Santos",
    estado: "Realizado",
    totalAlunos: 26,
    mediaResultado: 14.3,
  },
  {
    id: "EXM003",
    tipo: "Trabalho Prático",
    disciplinaId: "DIS001",
    disciplinaNome: "Programação Web",
    turmaId: "TUR002",
    turmaNome: "IG-3B",
    trimestre: "2º Trimestre",
    data: "2025-03-18",
    hora: "14:00",
    duracao: 180,
    sala: "Lab 2",
    professorId: "PROF001",
    professorNome: "Profª. Maria Santos",
    estado: "Realizado",
    totalAlunos: 26,
    mediaResultado: 15.8,
  },
  {
    id: "EXM004",
    tipo: "Exame",
    disciplinaId: "DIS002",
    disciplinaNome: "Base de Dados",
    turmaId: "TUR001",
    turmaNome: "IG-3A",
    trimestre: "2º Trimestre",
    data: "2025-03-27",
    hora: "08:00",
    duracao: 120,
    sala: "Sala 301",
    professorId: "PROF001",
    professorNome: "Profª. Maria Santos",
    estado: "Programado",
    totalAlunos: 28,
    mediaResultado: null,
  },
  {
    id: "EXM005",
    tipo: "Teste",
    disciplinaId: "DIS003",
    disciplinaNome: "Sistemas Operativos",
    turmaId: "TUR001",
    turmaNome: "IG-3A",
    trimestre: "1º Trimestre",
    data: "2025-01-15",
    hora: "10:00",
    duracao: 90,
    sala: "Lab 3",
    professorId: "PROF003",
    professorNome: "Prof. Manuel Gomes",
    estado: "Realizado",
    totalAlunos: 28,
    mediaResultado: 13.2,
  },
]

export const EXAME_RESULTADOS = [
  { exameId: "EXM002", alunoId: "ALU001", alunoNome: "João Manuel da Silva", nota: 16, estado: "Aprovado" },
  { exameId: "EXM002", alunoId: "ALU002", alunoNome: "Ana Beatriz Ferreira", nota: 14, estado: "Aprovado" },
  { exameId: "EXM002", alunoId: "ALU003", alunoNome: "Pedro Miguel Santos", nota: 11, estado: "Aprovado" },
  { exameId: "EXM002", alunoId: "ALU004", alunoNome: "Maria José Costa", nota: 18, estado: "Aprovado" },
  { exameId: "EXM002", alunoId: "ALU005", alunoNome: "Carlos Eduardo Gomes", nota: 8, estado: "Reprovado" },
]

// ─── Módulo 6: Financeiro ─────────────────────────────────────────────────────

export const PROPINAS = [
  // João Manuel da Silva – ALU001
  { id: "PRO001", alunoId: "ALU001", alunoNome: "João Manuel da Silva", turma: "IG-3A", curso: "Informática de Gestão", anoLectivo: "2024/2025", mes: "Janeiro", mesNum: 1, valorMensal: 15000, estado: "pago", dataVencimento: "2025-01-31", dataPagamento: "2025-01-20", referencia: "REF-2501-001" },
  { id: "PRO002", alunoId: "ALU001", alunoNome: "João Manuel da Silva", turma: "IG-3A", curso: "Informática de Gestão", anoLectivo: "2024/2025", mes: "Fevereiro", mesNum: 2, valorMensal: 15000, estado: "pago", dataVencimento: "2025-02-28", dataPagamento: "2025-02-15", referencia: "REF-2502-001" },
  { id: "PRO003", alunoId: "ALU001", alunoNome: "João Manuel da Silva", turma: "IG-3A", curso: "Informática de Gestão", anoLectivo: "2024/2025", mes: "Março", mesNum: 3, valorMensal: 15000, estado: "pendente", dataVencimento: "2025-03-31", dataPagamento: null, referencia: null },
  // Ana Beatriz Ferreira – ALU002
  { id: "PRO004", alunoId: "ALU002", alunoNome: "Ana Beatriz Ferreira", turma: "IG-3A", curso: "Informática de Gestão", anoLectivo: "2024/2025", mes: "Janeiro", mesNum: 1, valorMensal: 15000, estado: "pago", dataVencimento: "2025-01-31", dataPagamento: "2025-01-25", referencia: "REF-2501-002" },
  { id: "PRO005", alunoId: "ALU002", alunoNome: "Ana Beatriz Ferreira", turma: "IG-3A", curso: "Informática de Gestão", anoLectivo: "2024/2025", mes: "Fevereiro", mesNum: 2, valorMensal: 15000, estado: "atrasado", dataVencimento: "2025-02-28", dataPagamento: null, referencia: null },
  { id: "PRO006", alunoId: "ALU002", alunoNome: "Ana Beatriz Ferreira", turma: "IG-3A", curso: "Informática de Gestão", anoLectivo: "2024/2025", mes: "Março", mesNum: 3, valorMensal: 15000, estado: "pendente", dataVencimento: "2025-03-31", dataPagamento: null, referencia: null },
  // Carlos Eduardo Gomes – ALU005
  { id: "PRO007", alunoId: "ALU005", alunoNome: "Carlos Eduardo Gomes", turma: "IG-3A", curso: "Informática de Gestão", anoLectivo: "2024/2025", mes: "Janeiro", mesNum: 1, valorMensal: 15000, estado: "atrasado", dataVencimento: "2025-01-31", dataPagamento: null, referencia: null },
  { id: "PRO008", alunoId: "ALU005", alunoNome: "Carlos Eduardo Gomes", turma: "IG-3A", curso: "Informática de Gestão", anoLectivo: "2024/2025", mes: "Fevereiro", mesNum: 2, valorMensal: 15000, estado: "atrasado", dataVencimento: "2025-02-28", dataPagamento: null, referencia: null },
  // Luísa Helena Martins – ALU006
  { id: "PRO009", alunoId: "ALU006", alunoNome: "Luísa Helena Martins", turma: "CONT-3A", curso: "Contabilidade", anoLectivo: "2024/2025", mes: "Janeiro", mesNum: 1, valorMensal: 15000, estado: "pago", dataVencimento: "2025-01-31", dataPagamento: "2025-01-10", referencia: "REF-2501-006" },
  { id: "PRO010", alunoId: "ALU006", alunoNome: "Luísa Helena Martins", turma: "CONT-3A", curso: "Contabilidade", anoLectivo: "2024/2025", mes: "Fevereiro", mesNum: 2, valorMensal: 15000, estado: "pago", dataVencimento: "2025-02-28", dataPagamento: "2025-02-08", referencia: "REF-2502-006" },
  { id: "PRO011", alunoId: "ALU006", alunoNome: "Luísa Helena Martins", turma: "CONT-3A", curso: "Contabilidade", anoLectivo: "2024/2025", mes: "Março", mesNum: 3, valorMensal: 15000, estado: "pago", dataVencimento: "2025-03-31", dataPagamento: "2025-03-05", referencia: "REF-2503-006" },
]

export const PAGAMENTOS = [
  { id: "PAG001", propinaId: "PRO001", alunoId: "ALU001", alunoNome: "João Manuel da Silva", mes: "Janeiro", valor: 15000, metodoPagamento: "Numerário", referencia: "REF-2501-001", dataPagamento: "2025-01-20", recibo: "REC-001", caixeiro: "António Ferreira" },
  { id: "PAG002", propinaId: "PRO002", alunoId: "ALU001", alunoNome: "João Manuel da Silva", mes: "Fevereiro", valor: 15000, metodoPagamento: "Transferência", referencia: "REF-2502-001", dataPagamento: "2025-02-15", recibo: "REC-002", caixeiro: "António Ferreira" },
  { id: "PAG003", propinaId: "PRO004", alunoId: "ALU002", alunoNome: "Ana Beatriz Ferreira", mes: "Janeiro", valor: 15000, metodoPagamento: "Multicaixa", referencia: "REF-2501-002", dataPagamento: "2025-01-25", recibo: "REC-003", caixeiro: "António Ferreira" },
  { id: "PAG004", propinaId: "PRO009", alunoId: "ALU006", alunoNome: "Luísa Helena Martins", mes: "Janeiro", valor: 15000, metodoPagamento: "Numerário", referencia: "REF-2501-006", dataPagamento: "2025-01-10", recibo: "REC-004", caixeiro: "António Ferreira" },
  { id: "PAG005", propinaId: "PRO010", alunoId: "ALU006", alunoNome: "Luísa Helena Martins", mes: "Fevereiro", valor: 15000, metodoPagamento: "Numerário", referencia: "REF-2502-006", dataPagamento: "2025-02-08", recibo: "REC-005", caixeiro: "António Ferreira" },
  { id: "PAG006", propinaId: "PRO011", alunoId: "ALU006", alunoNome: "Luísa Helena Martins", mes: "Março", valor: 15000, metodoPagamento: "Transferência", referencia: "REF-2503-006", dataPagamento: "2025-03-05", recibo: "REC-006", caixeiro: "António Ferreira" },
]

export const FINANCEIRO_STATS = {
  totalPropinasAno: 18780000, // AOA
  totalRecebido: 10500000,
  totalPendente: 4560000,
  totalAtrasado: 3720000,
  taxaCobranca: 55.9,
  alunosEmDia: 687,
  alunosAtrasados: 312,
  alunosSemPagamento: 190,
}

export const EVOLUCAO_COBRANCA = [
  { mes: "Set", recebido: 1680000, pendente: 225000 },
  { mes: "Out", recebido: 1725000, pendente: 180000 },
  { mes: "Nov", recebido: 1800000, pendente: 105000 },
  { mes: "Dez", recebido: 1650000, pendente: 255000 },
  { mes: "Jan", recebido: 1890000, pendente: 15000 },
  { mes: "Fev", recebido: 1755000, pendente: 150000 },
]

// Relatórios pré-definidos
export const RELATORIOS_DISPONIVEIS = [
  {
    id: "REL001",
    nome: "Aproveitamento Geral",
    tipo: "academico",
    descricao: "Relatório de aproveitamento geral por curso e turma",
  },
  {
    id: "REL002",
    nome: "Desempenho por Disciplina",
    tipo: "academico",
    descricao: "Análise de desempenho por disciplina",
  },
  {
    id: "REL003",
    nome: "Comparativo Trimestral",
    tipo: "academico",
    descricao: "Comparação de médias entre trimestres",
  },
  {
    id: "REL004",
    nome: "Alunos Aprovados/Reprovados",
    tipo: "academico",
    descricao: "Lista de alunos por estado de aprovação",
  },
  {
    id: "REL005",
    nome: "Estatísticas de Matrículas",
    tipo: "administrativo",
    descricao: "Evolução de matrículas por ano",
  },
  {
    id: "REL006",
    nome: "Relatório de Professores",
    tipo: "administrativo",
    descricao: "Carga horária e turmas por professor",
  },
]
